name: lattice_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.26
  - fpylll
  - torchmetrics
  - pip
  - pip:
    - torch==2.9.1
    - torchvision==0.18.1
    - torchaudio==2.9.1
    - einops
    - estimator
    - joblib
    - matplotlib
    - pandas
    - polars
    - scikit-learn
    - scipy
    - tabulate
    - tqdm
    - wandb
    - chardet